export const GLOBAL_AIRLINES_300 = {
  // --- North America ---
  'AA': 'American Airlines',
  'UA': 'United Airlines',
  'DL': 'Delta Air Lines',
  'WN': 'Southwest Airlines',
  'AS': 'Alaska Airlines',
  'B6': 'JetBlue Airways',
  'NK': 'Spirit Airlines',
  'F9': 'Frontier Airlines',
  'HA': 'Hawaiian Airlines',
  'G4': 'Allegiant Air',
  'AC': 'Air Canada',
  'WS': 'WestJet',
  'AM': 'Aeromexico',
  'YV': 'Mesa Airlines',
  'OO': 'SkyWest Airlines',
  'PD': 'Porter Airlines',
  'TS': 'Air Transat',
  '4N': 'Air North',

  // --- Europe ---
  'LH': 'Lufthansa',
  'AF': 'Air France',
  'KL': 'KLM Royal Dutch Airlines',
  'BA': 'British Airways',
  'TK': 'Turkish Airlines',
  'FR': 'Ryanair',
  'U2': 'easyJet',
  'IB': 'Iberia',
  'LX': 'Swiss International Air Lines',
  'OS': 'Austrian Airlines',
  'TP': 'TAP Air Portugal',
  'SK': 'SAS (Scandinavian Airlines)',
  'EI': 'Aer Lingus',
  'AY': 'Finnair',
  'LO': 'LOT Polish Airlines',
  'UX': 'Air Europa',
  'A3': 'Aegean Airlines',
  'BT': 'airBaltic',
  'JU': 'Air Serbia',
  'KM': 'Air Malta',
  'SN': 'Brussels Airlines',
  'DY': 'Norwegian Air Shuttle',
  'W6': 'Wizz Air',
  'EW': 'Eurowings',
  'VS': 'Virgin Atlantic',
  'LS': 'Jet2.com',
  'VY': 'Vueling Airlines',
  'FI': 'Icelandair',
  'OK': 'Czech Airlines',
  'RO': 'TAROM',
  'FB': 'Bulgaria Air',
  'OU': 'Croatia Airlines',

  // --- Middle East & Africa ---
  'QR': 'Qatar Airways',
  'EK': 'Emirates',
  'EY': 'Etihad Airways',
  'SV': 'Saudia',
  'WY': 'Oman Air',
  'GF': 'Gulf Air',
  'RJ': 'Royal Jordanian',
  'KU': 'Kuwait Airways',
  'ME': 'Middle East Airlines',
  'FZ': 'flydubai',
  'G9': 'Air Arabia',
  'ET': 'Ethiopian Airlines',
  'MS': 'EgyptAir',
  'AT': 'Royal Air Maroc',
  'KQ': 'Kenya Airways',
  'SA': 'South African Airways',
  'WB': 'RwandAir',
  'DT': 'TAAG Angola Airlines',
  'AH': 'Air Algerie',
  'TU': 'Tunisair',
  'TC': 'Air Tanzania',

  // --- Asia & Pacific ---
  'SQ': 'Singapore Airlines',
  'CX': 'Cathay Pacific',
  'NH': 'ANA (All Nippon Airways)',
  'JL': 'Japan Airlines',
  'KE': 'Korean Air',
  'BR': 'EVA Air',
  'CI': 'China Airlines',
  'QF': 'Qantas',
  'NZ': 'Air New Zealand',
  'VA': 'Virgin Australia',
  'TG': 'Thai Airways',
  'VN': 'Vietnam Airlines',
  'GA': 'Garuda Indonesia',
  'MH': 'Malaysia Airlines',
  'PR': 'Philippine Airlines',
  'SQ': 'Singapore Airlines',
  'AI': 'Air India',
  '6E': 'IndiGo',
  'UK': 'Vistara',
  'SG': 'SpiceJet',
  'CZ': 'China Southern Airlines',
  'MU': 'China Eastern Airlines',
  'CA': 'Air China',
  'MF': 'Xiamen Airlines',
  'HU': 'Hainan Airlines',
  'ZH': 'Shenzhen Airlines',
  '3U': 'Sichuan Airlines',
  'SC': 'Shandong Airlines',
  'AK': 'AirAsia',
  'TR': 'Scoot',
  'JQ': 'Jetstar',
  'UO': 'HK Express',
  'OZ': 'Asiana Airlines',
  'KE': 'Korean Air',
  'JX': 'STARLUX Airlines',
  'VJ': 'VietJet Air',
  'PG': 'Bangkok Airways',
  'BI': 'Royal Brunei Airlines',
  'FJ': 'Fiji Airways',
  'SB': 'Aircalin',
  'TN': 'Air Tahiti Nui',
  'PX': 'Air Niugini',

  // --- South America ---
  'LA': 'LATAM Airlines',
  'AV': 'Avianca',
  'AD': 'Azul Brazilian Airlines',
  'G3': 'GOL Linhas Aereas',
  'AR': 'Aerolineas Argentinas',
  'H2': 'Sky Airline',
  'JA': 'JetSMART',
  'P5': 'Wingo',
  'OB': 'BoA (Boliviana de Aviacion)',
  'CM': 'Copa Airlines',

  // --- Extended List & Regional ---
  'A5': 'HOP!',
  'EN': 'Air Dolomiti',
  'JP': 'Adria Airways',
  'LG': 'Luxair',
  'V7': 'Volotea',
  'XY': 'Flynas',
  'PC': 'Pegasus Airlines',
  'KK': 'AtlasGlobal',
  '4O': 'Interjet',
  'VB': 'VivaAerobus',
  'Y4': 'Volaris',
  'KC': 'Air Astana',
  'HY': 'Uzbekistan Airways',
  '9U': 'Air Moldova',
  'A9': 'Georgian Airways',
  'B2': 'Belavia',
  'PS': 'Ukraine International Airlines',
  'BT': 'Air Baltic',
  'SU': 'Aeroflot',
  'S7': 'S7 Airlines',
  'U6': 'Ural Airlines',
  'UT': 'UTair Aviation',
  'FV': 'Rossiya Airlines',
  '4G': 'Gazpromavia',
  '6R': 'Alrosa',
  'YC': 'Yamal Airlines',
  'GL': 'Air Greenland',
  'TF': 'Braathens Regional Airlines',
  'WF': 'Wideroe',
  'BE': 'Flybe',
  'GR': 'Aurigny Air Services',
  'SI': 'Blue Islands',
  '8P': 'Pacific Coastal Airlines',
  '7F': 'First Air',
  '5T': 'Canadian North',
  'JV': 'Bearskin Airlines',
  '3H': 'Air Inuit',
  '8T': 'Air Tindi',
  'FAB': 'First Air',
  '9E': 'Endeavor Air',
  'PT': 'Piedmont Airlines',
  'MQ': 'Envoy Air',
  'YX': 'Republic Airways',
  'OH': 'PSA Airlines',
  'ZW': 'Air Wisconsin',
  'C5': 'CommuteAir',
  'EV': 'ExpressJet Airlines',
  'AX': 'Trans States Airlines',
  'CP': 'Compass Airlines',
  'G7': 'GoJet Airlines',
  'S5': 'Shuttle America',
  '9K': 'Cape Air',
  'KS': 'PenAir',
  '7H': 'Ravn Alaska',
  'WP': 'Island Air',
  'MW': 'Mokulele Airlines',
  '3M': 'Silver Airways',
  'XJ': 'Thai AirAsia X',
  'D7': 'AirAsia X',
  'XT': 'Indonesia AirAsia X',
  'Z2': 'Philippines AirAsia',
  'I5': 'AirAsia India',
  'FD': 'Thai AirAsia',
  'QZ': 'Indonesia AirAsia',
  'VZ': 'Thai VietJet Air',
  'QH': 'Bamboo Airways',
  'QV': 'Lao Airlines',
  'K6': 'Cambodia Angkor Air',
  '8M': 'Myanmar Airways International',
  'UB': 'Myanmar National Airlines',
  'RA': 'Nepal Airlines',
  'KB': 'Drukair',
  'B3': 'Bhutan Airlines',
  'BG': 'Biman Bangladesh Airlines',
  'BS': 'US-Bangla Airlines',
  'PK': 'Pakistan International Airlines',
  'ER': 'Serene Air',
  'PA': 'Airblue',
  'IF': 'Baghdad Arab Air',
  'IA': 'Iraqi Airways',
  'QB': 'Qeshm Air',
  'W5': 'Mahan Air',
  'EP': 'Iran Aseman Airlines',
  'Y9': 'Kish Air',
  'B9': 'Iran Air Tours',
  'NV': 'Karun Airlines',
  'HH': 'Taban Air',
  'IV': 'Windrose Airlines',
  '7W': 'Windrose Airlines',
  'QU': 'Azur Air Ukraine',
  'YE': 'YanAir',
  'UR': 'UTair-Ukraine',
  'B0': 'La Compagnie',
  'TX': 'Air Caraibes',
  'SS': 'Corsair International',
  'UU': 'Air Austral',
  'MK': 'Air Mauritius',
  'MD': 'Air Madagascar',
  'QM': 'Air Malawi',
  'TC': 'Air Tanzania',
  'PW': 'Precision Air',
  'V5': 'Aerovias DAP',
  'T6': 'Air Amarilla',
  'PU': 'Plus Ultra Lineas Aereas',
  '2K': 'Avianca Ecuador',
  '9N': 'Tropic Air',
  'KX': 'Cayman Airways',
  'BW': 'Caribbean Airlines',
  'PY': 'Surinam Airways',
  'UP': 'Bahamasair',
  'JY': 'interCaribbean Airways',
  'WM': 'Winair',
  'V0': 'Conviasa',
  'QL': 'Laser Airlines',
  '9V': 'Avior Airlines',
  'AW': 'Africa World Airlines',
  'QI': 'Ibom Air',
  'P4': 'Air Peace',
  'BU': 'Air Burkina',
  'HF': 'Air Cote d’Ivoire',
  'HC': 'Air Senegal',
  'VR': 'TACV Cabo Verde Airlines',
  'JM': 'Air Jamaica',
  'IJ': 'Spring Airlines Japan',
  'GK': 'Jetstar Japan',
  'MM': 'Peach Aviation',
  'BC': 'Skymark Airlines',
  '7C': 'Jeju Air',
  'BX': 'Air Busan',
  'LJ': 'Jin Air',
  'TW': 'T\'way Air',
  'ZE': 'Eastar Jet',
  'RS': 'Air Seoul',
  'NX': 'Air Macau',
  'UO': 'Hong Kong Express',
  'AE': 'Mandarin Airlines',
  'B7': 'Uni Air',
  'IT': 'Tigerair Taiwan',
  'FE': 'Far Eastern Air Transport',
  'GE': 'TransAsia Airways',
  '8L': 'Lucky Air',
  'PN': 'West Air',
  'AQ': '9 Air',
  'GY': 'Colorful Guizhou Airlines',
  'GJ': 'Loong Air',
  'KY': 'Kunming Airlines',
  'TV': 'Tibet Airlines',
  'NS': 'Hebei Airlines',
  'CN': 'Grand China Air',
  '8C': 'Air Transport International',
  '5Y': 'Atlas Air',
  'FX': 'FedEx Express',
  '5X': 'UPS Airlines',
  'PO': 'Polar Air Cargo',
  'KJ': 'Air Incheon',
  'LD': 'Air Hong Kong',
  'K4': 'Kalitta Air',
  'M6': 'Amerijet International',
  'N8': 'National Airlines',
  'RU': 'AirBridgeCargo',
  'VI': 'Volga-Dnepr Airlines',
  'CV': 'Cargolux',
  '7L': 'Silk Way West Airlines',
  'MP': 'Martinair',
  'QT': 'Avianca Cargo',
  'UC': 'LATAM Cargo Chile',
  'M3': 'LATAM Cargo Brasil',
  'L7': 'LATAM Cargo Colombia',
  'T7': 'Twin Jet',
  'C3': 'Trade Air',
  'CT': 'Alitalia CityLiner',
  'ZB': 'Monarch Airlines',
  'MT': 'Thomas Cook Airlines',
  'QS': 'Smartwings',
  '6H': 'Israir Airlines',
  'IZ': 'Arkia',
  'LY': 'El Al Israel Airlines',
  'KM': 'Air Malta',
  'JP': 'Adria Airways',
  'YM': 'Montenegro Airlines',
  'MG': 'Luxwing',
  'V6': 'VI Airlink',
  '8B': 'Caribbean Star Airlines',
  'U3': 'Avies',
  'WW': 'WOW air',
  'RE': 'Stobart Air',
  'WX': 'CityJet',
  'CL': 'Lufthansa CityLine',
  'ST': 'Germania',
  'V3': 'Carpatair',
  '2L': 'Helvetic Airways',
  'WK': 'Edelweiss Air',
  '3P': 'Air Philippines',
  '9W': 'Jet Airways',
  '6I': 'Air Alsie',
  'OV': 'Estonian Air',
  '7Y': 'Mann Yadanarpon Airlines',
  'YH': 'Yangon Airways',
  'YH': 'Susi Air',
  '8I': 'Insel Air',
  '7I': 'Insel Air Aruba',
  'WP': 'Island Air',
  'V4': 'Vieques Air Link',
  'KO': 'Alaska Central Express'
}